# backend/config/mongoid.yml

development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 5
        connect_timeout: 10
        socket_timeout: 5
        max_pool_size: 5
        min_pool_size: 1

test:
  clients:
    default:
      database: job_portal_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 5
        connect_timeout: 10
        socket_timeout: 5
        # 生產環境使用較大的連線池
        max_pool_size: 10
        min_pool_size: 2
        # 重試寫入操作
        retry_writes: true
        # 讀取偏好設定
        read:
          mode: :primary
        # 確保使用正確的認證機制
        auth_mech: :scram
        auth_source: 'job_portal' # <--- 核心修改：明確指定 auth_source