development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "development_secret_key_that_is_very_long_and_secure_123456789" %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "test_secret_key_that_is_very_long_and_secure_123456789" %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
