services:
  backend:
    build: 
      context: .  # 改為根目錄
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      MONGODB_URI: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER_HOST}/${MONGODB_DATABASE}?retryWrites=true&w=majority&appName=${MONGODB_APP_NAME}
      SECRET_KEY_BASE: ${DEV_SECRET_KEY_BASE}
    volumes:
      - ./backend:/app:cached
      - ./data:/app/data
      - backend_bundle:/usr/local/bundle
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails server -b 0.0.0.0"

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  backend_bundle:
    driver: local